### ISSUE TITLE
@embroider/macros v1.11 fails the build in no-glint addons

### ISSUE THREAD

**Issue by andreyfel** [embroider-build/embroider#1452]
We have a bunch of addons and apps in a single yarn workspace. We don't use embroider and don't use glint.
We only use `@embroider/test-setup` in the addons.

When we bump the dependency `@embroider/macros` to v1.11 we start getting an error `Cannot find module '@glint/template' or its corresponding type declarations.`.

**Comment by void-mAlex** [comment]
hello @andreyfel
what version of yarn are you using 1.11+?
as of v1.11 @emboider/macros does declare @glint/template as an optional peerDependency but it's optional yarn should understand that from that version onward (currently latest being 1.22.11)
also are you getting that error in tests or builds?

**Comment by andreyfel** [comment]
We use yarn 1.22.18.
If @glint/template is an optional dependency it should work without it, right?
The error appears in builds.

**Comment by andreyfel** [comment]
I guess the fact that this dependency is optional makes sense for projects without TypeScript.

**Comment by void-mAlex** [comment]
@andreyfel have you gotten the build to work? if not we should reopen this issue, otherwise can you let others know what you needed to do to solve the issue?

**Comment by andreyfel** [comment]
I've added `@glint/template` to `devDependencies` of the app and it made the build work.
