### ISSUE TITLE
Cannot find module 'ember-source/vendor/ember/ember-template-compiler' with Ember 3.13.0-beta.3

### ISSUE THREAD

**Issue by josemarluedke** [embroider-build/embroider#311]
Upgrading to Ember 3.13.0-beta.3 fails to build with the following error: 

```
Build Error (WaitForTrees)

Cannot find module 'ember-source/vendor/ember/ember-template-compiler' from '/private/var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T/embroider/033c91'
```

This issue is probably due to this PR: https://github.com/emberjs/ember.js/pull/18208

<details><summary>Stack trace</summary>

```
=================================================================================

ENV Summary:

  TIME: Tue Aug 20 2019 08:36:48 GMT-0700 (Pacific Daylight Time)
  TITLE: ember
  ARGV:
  - /Users/josemarluedke/.volta/tools/image/node/12.6.0/6.9.0/bin/node
  - /Users/josemarluedke/code/my-app/node_modules/.bin/ember
  - s
  EXEC_PATH: /Users/josemarluedke/.volta/tools/image/node/12.6.0/6.9.0/bin/node
  TMPDIR: /var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/josemarluedke/.volta/tools/image/node/12.6.0/6.9.0/bin
  - /Users/josemarluedke/.volta/tools/image/yarn/1.16.0/bin
  - /Users/josemarluedke/.yarn/bin
  - /Users/josemarluedke/.config/yarn/global/node_modules/.bin
  - /Users/josemarluedke/.rbenv/shims
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /Library/TeX/texbin
  - /usr/local/MacGPG2/bin
  - /Users/josemarluedke/code/go/bin
  - /Users/josemarluedke/.fzf/bin
  PLATFORM: darwin x64
  FREEMEM: 565899264
  TOTALMEM: 17179869184
  UPTIME: 1204147
  LOADAVG: 2.7265625,2.564453125,2.42724609375
  CPUS:
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz - 2900
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - llhttp: 1.1.4
  - modules: 72
  - napi: 4
  - nghttp2: 1.38.0
  - node: 12.6.0
  - openssl: 1.1.1c
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.30.1
  - v8: 7.5.288.22-node.14
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Cannot find module 'ember-source/vendor/ember/ember-template-compiler' from '/private/var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T/embroider/033c91'
    at Function.module.exports [as sync] (/Users/josemarluedke/code/oss/embroider/node_modules/resolve/lib/sync.js:58:15)
    at AppBuilder.templateCompiler (/Users/josemarluedke/code/oss/embroider/packages/core/src/app.ts:680:29)
    at AppBuilder.build (/Users/josemarluedke/code/oss/embroider/packages/core/src/app.ts:612:33)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at WaitForTrees.buildHook (/Users/josemarluedke/code/oss/embroider/packages/core/src/build-stage.ts:39:7)
  - code: [undefined]
  - codeFrame: Cannot find module 'ember-source/vendor/ember/ember-template-compiler' from '/private/var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T/embroider/033c91'
  - errorMessage: Cannot find module 'ember-source/vendor/ember/ember-template-compiler' from '/private/var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T/embroider/033c91'
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (/Users/josemarluedke/code/oss/embroider/node_modules/broccoli-plugin/index.js:7:31)
    at new WaitForTrees (/Users/josemarluedke/code/oss/embroider/packages/core/src/wait-for-trees.ts:30:5)
    at CompatApp.get tree (/Users/josemarluedke/code/oss/embroider/packages/core/src/build-stage.ts:28:12)
    at CompatApp.<anonymous> (/Users/josemarluedke/code/oss/embroider/node_modules/typescript-memoize/src/memoize-decorator.ts:60:36)
    at new PackagerRunner (/Users/josemarluedke/code/oss/embroider/packages/core/src/to-broccoli-plugin.ts:13:20)
    at Object.defaultPipeline [as compatBuild] (/Users/josemarluedke/code/oss/embroider/packages/compat/src/default-pipeline.ts:47:10)
    at module.exports (/Users/josemarluedke/code/my-app/ember-cli-build.js:15:39)
    at Builder.readBuildFile (/Users/josemarluedke/code/my-app/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/josemarluedke/code/my-app/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/josemarluedke/code/my-app/node_modules/ember-cli/lib/models/builder.js:32:10)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Cannot find module 'ember-source/vendor/ember/ember-template-compiler' from '/private/var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T/embroider/033c91'
        at WaitForTrees (@embroider/compat/app)
-~- created here: -~-
    at new Plugin (/Users/josemarluedke/code/oss/embroider/node_modules/broccoli-plugin/index.js:7:31)
    at new WaitForTrees (/Users/josemarluedke/code/oss/embroider/packages/core/src/wait-for-trees.ts:30:5)
    at CompatApp.get tree (/Users/josemarluedke/code/oss/embroider/packages/core/src/build-stage.ts:28:12)
    at CompatApp.<anonymous> (/Users/josemarluedke/code/oss/embroider/node_modules/typescript-memoize/src/memoize-decorator.ts:60:36)
    at new PackagerRunner (/Users/josemarluedke/code/oss/embroider/packages/core/src/to-broccoli-plugin.ts:13:20)
    at Object.defaultPipeline [as compatBuild] (/Users/josemarluedke/code/oss/embroider/packages/compat/src/default-pipeline.ts:47:10)
    at module.exports (/Users/josemarluedke/code/my-app/ember-cli-build.js:15:39)
    at Builder.readBuildFile (/Users/josemarluedke/code/my-app/node_modules/ember-cli/lib/models/builder.js:52:14)
    at Builder.setupBroccoliBuilder (/Users/josemarluedke/code/my-app/node_modules/ember-cli/lib/models/builder.js:66:22)
    at new Builder (/Users/josemarluedke/code/my-app/node_modules/ember-cli/lib/models/builder.js:32:10)
-~- (end) -~-
  - name: BuildError
  - nodeAnnotation: @embroider/compat/app
  - nodeName: WaitForTrees
  - originalErrorMessage: Cannot find module 'ember-source/vendor/ember/ember-template-compiler' from '/private/var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T/embroider/033c91'
  - stack: Error: Cannot find module 'ember-source/vendor/ember/ember-template-compiler' from '/private/var/folders/67/6jb5flcd6d30lkgvj0_92c_m0000gn/T/embroider/033c91'
    at Function.module.exports [as sync] (/Users/josemarluedke/code/oss/embroider/node_modules/resolve/lib/sync.js:58:15)
    at AppBuilder.templateCompiler (/Users/josemarluedke/code/oss/embroider/packages/core/src/app.ts:680:29)
    at AppBuilder.build (/Users/josemarluedke/code/oss/embroider/packages/core/src/app.ts:612:33)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at WaitForTrees.buildHook (/Users/josemarluedke/code/oss/embroider/packages/core/src/build-stage.ts:39:7)

=================================================================================
```
</details>

**Comment by josemarluedke** [comment]
Will be fixed by https://github.com/emberjs/ember.js/pull/18291

**Comment by NullVoxPopuli** [comment]
@josemarluedke was this fixed?

**Comment by patrickberkeley** [comment]
I'm seeing the same error when trying to get embroider working on an Ember 3.26.1 addon.

**Comment by NullVoxPopuli** [comment]
I have the template compiler working in 3.27

**Comment by ef4** [comment]
On recent releases, I have only been able to reproduce this failure in odd situations where ember-source has actually been included twice. For example, it can happen due to package name aliasing:

```js
"devDependencies": {
   "ember-source": "~3.27.2",
   "ember-source-lts": "npm:ember-source@~3.20.0",
}
```

Possibly unusual monorepo setups can also trigger this.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.
