### ISSUE TITLE
Build fails after upgrading to 0.37 (Cannot find module '@babel/helper-regex')

### ISSUE THREAD

**Issue by gojefferson** [embroider-build/embroider#719]
Here's the stack trace:

```
~/cf_repos/cfapp/web> ember deploy sandbox --activate=true
cleaning up...
- build failed
Error: jquery/component.dollar.js: [BABEL]: Cannot find module '@babel/helper-regex'
Require stack:
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/helper-create-regexp-features-plugin/lib/index.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/plugin-proposal-unicode-property-regex/lib/index.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/preset-env/lib/available-plugins.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/preset-env/lib/plugins-compat-data.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/preset-env/lib/normalize-options.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/preset-env/lib/index.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/index.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/index.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/broccoli-babel-transpiler/lib/worker.js (While processing: /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/preset-env/lib/index.js)
        in /Users/tjkerr/cf_repos/cfapp/web/node_modules/@ember/jquery/vendor
        at broccoli-persistent-filter:Babel > [Babel: casefleet-web] (Babel: casefleet-web)
        at OneShot
-~- created here: -~-
    at new Plugin (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/node_modules/broccoli-plugin/dist/index.js:45:33)
    at new OneShot (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/src/one-shot.js:14:9)
    at Object.cachedBuildCompatAddon [as default] (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/src/build-compat-addon.js:15:16)
    at /Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/src/compat-addons.js:45:105
    at Array.map (<anonymous>)
    at CompatAddons.get tree [as tree] (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/src/compat-addons.js:45:63)
    at CompatApp.augment (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/core/src/build-stage.js:57:64)
    at CompatApp.get tree (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/core/src/build-stage.js:26:50)
    at CompatApp.<anonymous> (/Users/tjkerr/cf_repos/cfapp/web/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at new PackagerRunner (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:26)
    at Object.defaultPipeline (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/src/default-pipeline.js:43:12)
    at module.exports (/Users/tjkerr/cf_repos/cfapp/web/ember-cli-build.js:67:39)
    at Builder.readBuildFile (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli/lib/models/builder.js:29:10)
    at Class.build (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-deploy-build/index.js:30:23)
    at Object.fn (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:93:21)
    at Pipeline._notifyPipelinePluginHookExecution (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-deploy/lib/models/pipeline.js:173:19)
    at tryCatch (/Users/tjkerr/cf_repos/cfapp/web/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/tjkerr/cf_repos/cfapp/web/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/tjkerr/cf_repos/cfapp/web/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/tjkerr/cf_repos/cfapp/web/node_modules/rsvp/dist/rsvp.js:2415:5)
-~- (end) -~-
Error: [BABEL]: Cannot find module '@babel/helper-regex'
Require stack:
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/helper-create-regexp-features-plugin/lib/index.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/plugin-proposal-unicode-property-regex/lib/index.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/preset-env/lib/available-plugins.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/preset-env/lib/plugins-compat-data.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/preset-env/lib/normalize-options.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/preset-env/lib/index.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/module-types.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/configuration.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/config/files/index.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/broccoli-babel-transpiler/node_modules/@babel/core/lib/index.js
- /Users/tjkerr/cf_repos/cfapp/web/node_modules/broccoli-babel-transpiler/lib/worker.js (While processing: /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/preset-env/lib/index.js)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-babel/node_modules/@babel/helper-create-regexp-features-plugin/lib/index.js:18:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)Pipeline aborted
```

**Comment by gojefferson** [comment]
After installing @babel/helper-regex and @babel/helper-define-map, it now appears the problem is related to ember-basic-dropdown:

```
~/cf_repos/cfapp/web> ember deploy sandbox --activate=true
cleaning up...
- build failed
Error: templates/components/basic-dropdown-content.hbs: Cannot read property 'line' of undefined
        in /var/folders/4y/k131xw0n4b34wvt77_sn6rkw0000gn/T/broccoli-4874835ysNxPcd94B/out-02-broccoli_persistent_filter_babel_babel_ember_basic_dropd
        at embroider-template-compile-stage1
        at OneShot
-~- created here: -~-
    at new Plugin (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/node_modules/broccoli-plugin/dist/index.js:45:33)
    at new OneShot (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/src/one-shot.js:14:9)
    at Object.cachedBuildCompatAddon [as default] (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/src/build-compat-addon.js:15:16)
    at /Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/src/compat-addons.js:45:105
    at Array.map (<anonymous>)
    at CompatAddons.get tree [as tree] (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/src/compat-addons.js:45:63)
    at CompatApp.augment (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/core/src/build-stage.js:57:64)
    at CompatApp.get tree (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/core/src/build-stage.js:26:50)
    at CompatApp.<anonymous> (/Users/tjkerr/cf_repos/cfapp/web/node_modules/typescript-memoize/dist/memoize-decorator.js:67:52)
    at new PackagerRunner (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/core/src/to-broccoli-plugin.js:10:26)
    at Object.defaultPipeline (/Users/tjkerr/cf_repos/cfapp/web/node_modules/@embroider/compat/src/default-pipeline.js:43:12)
    at module.exports (/Users/tjkerr/cf_repos/cfapp/web/ember-cli-build.js:67:39)
    at Builder.readBuildFile (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli/lib/models/builder.js:49:14)
    at Builder.setupBroccoliBuilder (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli/lib/models/builder.js:63:22)
    at new Builder (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli/lib/models/builder.js:29:10)
    at Class.build (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-deploy-build/index.js:30:23)
    at Object.fn (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:93:21)
    at Pipeline._notifyPipelinePluginHookExecution (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-cli-deploy/lib/models/pipeline.js:173:19)
    at tryCatch (/Users/tjkerr/cf_repos/cfapp/web/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/tjkerr/cf_repos/cfapp/web/node_modules/rsvp/dist/rsvp.js:538:13)
    at /Users/tjkerr/cf_repos/cfapp/web/node_modules/rsvp/dist/rsvp.js:606:14
    at flush (/Users/tjkerr/cf_repos/cfapp/web/node_modules/rsvp/dist/rsvp.js:2415:5)
-~- (end) -~-
TypeError: Cannot read property 'line' of undefined
    at sortByLoc (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-source/dist/ember-template-compiler.js:10803:29)
    at Array.sort (<anonymous>)
    at Printer.OpenElementNode (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-source/dist/ember-template-compiler.js:11035:71)
    at Printer.ElementNode (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-source/dist/ember-template-compiler.js:11028:12)
    at Printer.TopLevelStatement (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-source/dist/ember-template-compiler.js:10961:23)
    at /Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-source/dist/ember-template-compiler.js:11019:23
    at Array.forEach (<anonymous>)
    at Printer.TopLevelStatements (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-source/dist/ember-template-compiler.js:11018:18)
    at Printer.Block (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-source/dist/ember-template-compiler.js:11012:12)
    at Printer.BlockStatement (/Users/tjkerr/cf_repos/cfapp/web/node_modules/ember-source/dist/ember-template-compiler.js:11162:12)Pipeline aborted
~/cf_repos/cfapp/web>
```

**Comment by ef4** [comment]
Hi Jeff, what ember-source version is this?

**Comment by gojefferson** [comment]
Hey Ed,

It's ember-source@3.25.3

**Comment by void-mAlex** [comment]
@gojefferson could you confirm if this is still an issue please?
