### ISSUE TITLE
`@embroider/addon-shim` does not have valid "main" entry in package.json

### ISSUE THREAD

**Issue by s1gr1d** [embroider-build/embroider#2609]
Hello 👋 

With the latest version `1.10.1`, we are getting this error [in CI](https://github.com/getsentry/sentry-javascript/actions/runs/19270261777/job/55100741708): 

```
Error: Cannot find module '/home/runner/work/_temp/test-application/node_modules/.pnpm/ember-modifier@4.2.2_@babel+core@7.28.5/node_modules/@embroider/addon-shim/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:524:19)
    at Module._findPath (node:internal/modules/cjs/loader:792:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1405:27)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1058:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1063:22)
    at Module._load (node:internal/modules/cjs/loader:1226:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
    at Module.require (node:internal/modules/cjs/loader:1503:12)
    at require (node:internal/modules/helpers:152:16)
```

This must be the suspect commit: https://github.com/embroider-build/embroider/commit/d4355436d63606caf79fcd76bcc70a6a280959c3

**Comment by s1gr1d** [comment]
Can confirm that it works with `10.0.2`. Thank you all for the quick resolution!
